// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2");

            modelBuilder.Entity("FinalProject.Models.AttendEvent", b =>
                {
                    b.Property<int>("eventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("personId")
                        .HasColumnType("INTEGER");

                    b.HasKey("eventId", "personId");

                    b.HasIndex("personId");

                    b.ToTable("AttendEvent");
                });

            modelBuilder.Entity("FinalProject.Models.Event", b =>
                {
                    b.Property<int>("eventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("eventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("eventDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("eventName")
                        .HasColumnType("TEXT");

                    b.Property<string>("streetLocation")
                        .HasColumnType("TEXT");

                    b.HasKey("eventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("FinalProject.Models.Person", b =>
                {
                    b.Property<int>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<long>("phoneNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("personId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FinalProject.Models.AttendEvent", b =>
                {
                    b.HasOne("FinalProject.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("eventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("personId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
